---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubernetes-lamp-demo-db-pv
  labels:
    app: kubernetes-lamp-demo
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /nfsroot/docker/alltiersolutions/kubernetes-lamp-demo/mysqldata
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default-storage
